#!/usr/bin/env python3

import sys
from pathlib import Path


import tomllib

from runcommand import run

with open(Path.joinpath(Path(__file__).parent, "packages.toml"), "rb") as f:
    data = tomllib.load(f)
    groups = data.keys()

if __name__ == "__main__":
    args = set(filter(lambda a: a in groups, sys.argv[1:]))

    if not args:
        print(f"Usage: bootstrap_environment.py [{'|'.join(groups)}]")
        sys.exit(1)

    packages = [p for a in args for p in data[a]]

    run(["sudo", "dnf", "install", "-y", *packages])
